version: "3.0"
services:

  db:
    hostname: Eis-db
    image: mariadb:11.3.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: Eis
    volumes:
      - db-storage:/var/lib/mysql
      - ./config/mariadb/dbUser.sql:/docker-entrypoint-initdb.d/1.sql
      - ./config/mariadb/login.sql:/docker-entrypoint-initdb.d/2.sql
      - ./config/mariadb/users.sql:/docker-entrypoint-initdb.d/3.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mariadb-admin","ping", "-uroot", "-p${DB_ROOT_PASSWORD}" ]
      interval: 20s
      timeout: 10s
      retries: 3
    env_file:
      - .env

  php-fpm:
    hostname: eis-php
    image: php:8.1-fpm
    command: bash -c "apt-get update && apt-get install -y libssl-dev && if ! pecl list | grep -q mongodb; then pecl install mongodb; fi && docker-php-ext-install mysqli pdo pdo_mysql  && docker-php-ext-enable mysqli pdo pdo_mysql mongodb && echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/mongodb.ini && pecl config-set php_ini /etc/php.ini &&  php-fpm"
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "php-fpm", "-v" ]
      interval: 20s
      timeout: 10s
      retries: 3

  nginx:
    hostname: eis-nginx
    image: nginx:1.25.5
    volumes:
      - ./src:/var/www/html/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 20s
      retries: 5
      timeout: 10s

volumes:
  db-storage:
  mongodb-storage: